# this is a sample config file showing how to define config parameters for
# the ddh module. Once valid credentials are defined, the file can live in one
# of these locations:
# ~/.ddh_config.yaml (preferred)
# {CWD}/config.yaml (deprecated)
datacatalog.worldbank.org:
  user:     YOUR_USERNAME
  password: YOUR_PASSWORD
  # protocol is optional: defaults to https
  protocol: https
